"""
Cross-language hash vector verification.

Loads fixtures/hash-vectors.json (generated by Python, verified by TypeScript)
and confirms the Python hash module reproduces every canonical form and SHA-256.
All 16 vectors must match — any deviation means cross-language hashes diverge.
"""

import json
from pathlib import Path

import pytest

from talonsight_ontology.hash import canonicalize, hash_artifact, verify

FIXTURES = Path(__file__).resolve().parent.parent.parent / "fixtures" / "hash-vectors.json"


@pytest.fixture(scope="module")
def vectors() -> list[dict]:
    with open(FIXTURES) as f:
        data = json.load(f)
    return data["vectors"]


class TestCanonicalHash:
    """Verify every fixture vector."""

    def test_fixture_file_exists(self):
        assert FIXTURES.exists(), f"Missing {FIXTURES}"

    def test_all_vectors_canonical(self, vectors):
        for v in vectors:
            result = canonicalize(v["input"])
            assert result == v["canonical"], (
                f"[{v['name']}] canonical mismatch:\n"
                f"  got:      {result}\n"
                f"  expected: {v['canonical']}"
            )

    def test_all_vectors_hash(self, vectors):
        for v in vectors:
            result = hash_artifact(v["input"])
            assert result == v["hash"], (
                f"[{v['name']}] hash mismatch:\n"
                f"  got:      {result}\n"
                f"  expected: {v['hash']}"
            )

    def test_verify_positive(self, vectors):
        for v in vectors:
            assert verify(v["input"], v["hash"]), f"[{v['name']}] verify should pass"

    def test_verify_negative(self, vectors):
        for v in vectors:
            assert not verify(v["input"], "0" * 64), f"[{v['name']}] verify should fail on wrong hash"

    def test_vector_count(self, vectors):
        assert len(vectors) == 16, f"Expected 16 vectors, got {len(vectors)}"


class TestHashEdgeCases:
    """Extra edge cases beyond the fixture vectors."""

    def test_empty_object(self):
        assert hash_artifact({}) == hash_artifact({})

    def test_key_order_irrelevant(self):
        assert hash_artifact({"b": 1, "a": 2}) == hash_artifact({"a": 2, "b": 1})

    def test_nested_key_order(self):
        a = {"outer": {"z": 1, "a": 2}}
        b = {"outer": {"a": 2, "z": 1}}
        assert hash_artifact(a) == hash_artifact(b)

    def test_none_preserved(self):
        assert hash_artifact({"a": None}) != hash_artifact({})

    def test_array_order_preserved(self):
        assert hash_artifact([1, 2, 3]) != hash_artifact([3, 2, 1])

    def test_hash_format(self):
        h = hash_artifact({"test": True})
        assert len(h) == 64
        assert all(c in "0123456789abcdef" for c in h)

    def test_unicode_stability(self):
        h1 = hash_artifact({"emoji": "🔥"})
        h2 = hash_artifact({"emoji": "🔥"})
        assert h1 == h2
